package com.orcharddu.fitty.dataholder

import com.orcharddu.fitty.model.Exercise
import com.orcharddu.fitty.model.Food

object Labels {

    val foodLabels = listOf(
        Food(name = "Apple pie",                calorie = 237, weights = 100),
        Food(name = "Baby back ribs",           calorie = 310, weights = 100),
        Food(name = "Baklava",                  calorie = 428, weights = 100),
        Food(name = "Beef carpaccio",           calorie = 119, weights = 100),
        Food(name = "Beef tartare",             calorie = 210, weights = 100),
        Food(name = "Beet salad",               calorie = 159, weights = 100),
        Food(name = "Beignets",                 calorie = 452, weights = 100),
        Food(name = "Bibimbap",                 calorie = 79, weights = 100),
        Food(name = "Bread pudding",            calorie = 153, weights = 100),
        Food(name = "Breakfast burrito",        calorie = 202, weights = 100),
        Food(name = "Bruschetta",               calorie = 70, weights = 100),
        Food(name = "Caesar salad",             calorie = 44, weights = 100),
        Food(name = "Cannoli",                  calorie = 254, weights = 100),
        Food(name = "Caprese salad",            calorie = 148, weights = 100),
        Food(name = "Carrot cake",              calorie = 414, weights = 100),
        Food(name = "Ceviche",                  calorie = 69, weights = 100),
        Food(name = "Cheese plate",             calorie = 359, weights = 100),
        Food(name = "Cheesecake",               calorie = 321, weights = 100),
        Food(name = "Chicken curry",            calorie = 109, weights = 100),
        Food(name = "Chicken quesadilla",       calorie = 306, weights = 100),
        Food(name = "Chicken wings",            calorie = 203, weights = 100),
        Food(name = "Chocolate cake",           calorie = 370, weights = 100),
        Food(name = "Chocolate mousse",         calorie = 209, weights = 100),
        Food(name = "Churros",                  calorie = 447, weights = 100),
        Food(name = "Clam chowder",             calorie = 55, weights = 100),
        Food(name = "Club sandwich",            calorie = 220, weights = 100),
        Food(name = "Crab cakes",               calorie = 266, weights = 100),
        Food(name = "Creme brulee",             calorie = 336, weights = 100),
        Food(name = "Croque madame",            calorie = 231, weights = 100),
        Food(name = "Cup cakes",                calorie = 305, weights = 100),
        Food(name = "Deviled eggs",             calorie = 201, weights = 100),
        Food(name = "Donuts",                   calorie = 452, weights = 100),
        Food(name = "Dumplings",                calorie = 124, weights = 100),
        Food(name = "Edamame",                  calorie = 121, weights = 100),
        Food(name = "Eggs benedict",            calorie = 276, weights = 100),
        Food(name = "Escargots",                calorie = 90, weights = 100),
        Food(name = "Falafel",                  calorie = 332, weights = 100),
        Food(name = "Filet mignon",             calorie = 267, weights = 100),
        Food(name = "Fish and chips",           calorie = 212, weights = 100),
        Food(name = "Foie gras",                calorie = 462, weights = 100),
        Food(name = "French fries",             calorie = 311, weights = 100),
        Food(name = "French onion soup",        calorie = 22, weights = 100),
        Food(name = "French toast",             calorie = 229, weights = 100),
        Food(name = "Fried calamari",           calorie = 174, weights = 100),
        Food(name = "Fried rice",               calorie = 163, weights = 100),
        Food(name = "Frozen yogurt",            calorie = 158, weights = 100),
        Food(name = "Garlic bread",             calorie = 349, weights = 100),
        Food(name = "Gnocchi",                  calorie = 1000, weights = 100),
        Food(name = "Greek salad",              calorie = 133, weights = 100),
        Food(name = "Grilled cheese sandwich",  calorie = 350, weights = 100),
        Food(name = "Grilled salmon",           calorie = 171, weights = 100),
        Food(name = "Guacamole",                calorie = 157, weights = 100),
        Food(name = "Gyoza",                    calorie = 287, weights = 100),
        Food(name = "Hamburger",                calorie = 294, weights = 100),
        Food(name = "Hot and sour soup",        calorie = 38, weights = 100),
        Food(name = "Hot dog",                  calorie = 289, weights = 100),
        Food(name = "Huevos rancheros",         calorie = 119, weights = 100),
        Food(name = "Hummus",                   calorie = 166, weights = 100),
        Food(name = "Ice cream",                calorie = 207, weights = 100),
        Food(name = "Lasagna",                  calorie = 134, weights = 100),
        Food(name = "Lobster bisque",           calorie = 50, weights = 100),
        Food(name = "Lobster roll sandwich",    calorie = 436, weights = 100),
        Food(name = "Macaroni and cheese",      calorie = 164, weights = 100),
        Food(name = "Macarons",                 calorie = 457, weights = 100),
        Food(name = "Miso soup",                calorie = 35, weights = 100),
        Food(name = "Mussels",                  calorie = 172, weights = 100),
        Food(name = "Nachos",                   calorie = 305, weights = 100),
        Food(name = "Omelette",                 calorie = 153, weights = 100),
        Food(name = "Onion rings",              calorie = 410, weights = 100),
        Food(name = "Oysters",                  calorie = 198, weights = 100),
        Food(name = "Pad thai",                 calorie = 114, weights = 100),
        Food(name = "Paella",                   calorie = 158, weights = 100),
        Food(name = "Pancakes",                 calorie = 227, weights = 100),
        Food(name = "Panna cotta",              calorie = 375, weights = 100),
        Food(name = "Peking duck",              calorie = 336, weights = 100),
        Food(name = "Pho",                      calorie = 67, weights = 100),
        Food(name = "Pizza",                    calorie = 266, weights = 100),
        Food(name = "Pork chop",                calorie = 230, weights = 100),
        Food(name = "Poutine",                  calorie = 233, weights = 100),
        Food(name = "Prime rib",                calorie = 266, weights = 100),
        Food(name = "Pulled pork sandwich",     calorie = 237, weights = 100),
        Food(name = "Ramen",                    calorie = 436, weights = 100),
        Food(name = "Ravioli",                  calorie = 77, weights = 100),
        Food(name = "Red velvet cake",          calorie = 367, weights = 100),
        Food(name = "Risotto",                  calorie = 174, weights = 100),
        Food(name = "Samosa",                   calorie = 308, weights = 100),
        Food(name = "Sashimi",                  calorie = 146, weights = 100),
        Food(name = "Scallops",                 calorie = 111, weights = 100),
        Food(name = "Seaweed salad",            calorie = 45, weights = 100),
        Food(name = "Shrimp and grits",         calorie = 45, weights = 100),
        Food(name = "Spaghetti bolognese",      calorie = 113, weights = 100),
        Food(name = "Spaghetti carbonara",      calorie = 191, weights = 100),
        Food(name = "Spring rolls",             calorie = 153, weights = 100),
        Food(name = "Steak",                    calorie = 270, weights = 100),
        Food(name = "Strawberry shortcake",     calorie = 346, weights = 100),
        Food(name = "Sushi",                    calorie = 143, weights = 100),
        Food(name = "Tacos",                    calorie = 226, weights = 100),
        Food(name = "Takoyaki",                 calorie = 131, weights = 100),
        Food(name = "Tiramisu",                 calorie = 283, weights = 100),
        Food(name = "Tuna tartare",             calorie = 202, weights = 100),
        Food(name = "Waffles",                  calorie = 291, weights = 100),
    )

    val exercisePlans = listOf(
        Exercise(
            calorieFactor = 8.2,
            name = "JOGGING",
            icon = Resources.Icon.JOGGING,
            checked = false),
        Exercise(
            calorieFactor = 9.3,
            name = "RIDING",
            icon = Resources.Icon.RIDING,
            checked = false),
        Exercise(
            calorieFactor = 8.2,
            name = "ROWING",
            icon = Resources.Icon.ROWING,
            checked = false),
        Exercise(
            calorieFactor = 8.5,
            name = "TENNIS",
            icon = Resources.Icon.TENNIS,
            checked = false),
        Exercise(
            calorieFactor = 4.7,
            name = "TABLE TENNIS",
            icon = Resources.Icon.TABLE_TENNIS,
            checked = false),
        Exercise(
            calorieFactor = 11.7,
            name = "SOCCER",
            icon = Resources.Icon.SOCCER,
            checked = false),
        Exercise(
            calorieFactor = 9.3,
            name = "BASKETBALL",
            icon = Resources.Icon.BASKETBALL,
            checked = false),
    )

}